name: Terraform Plan
on: [pull_request]

jobs:
  lint:
    name: Terraform Format check
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          teraform_version: v1.9.7
          terraform_wrapper: false
      
      - name: terraform FMT
        run: |
          terraform fmt -check -diff
          cd environments && terraform fmt -check -recursive -diff
          