name: Terraform Plan
on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Terraform Format check
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.9.7
          terraform_wrapper: false
      
      - name: terraform FMT
        run: |
          terraform fmt -check -diff
          cd environments && terraform fmt -check -recursive -diff

  Get_Changes:
    needs: lint
    runs-on: [ubuntu-latest]
    outputs:
      envs: ${{ steps.detect.outputs.envs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect Changes
        id: detect
        run: |
          changes=$(python ./scripts/git-diff.py | tr -d '\r')
          echo "envs=$changes" >> "$GITHUB_OUTPUT"

  Terraform_Plan:
    runs-on: [ubuntu-latest]
    needs: [lint, Get_Changes]
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.Get_Changes.outputs.envs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.9.7
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::941377147400:role/GitHub-Role
      
      - name: Initialize terraform 
        run: |
          terraform init
          terraform workspace select ${{matrix.workspace}}

      - name: Terraform Plan
        run: |
          terraform plan -no-color

