# #This is the Github workflow template that will be used to create the workflows for all the different Envs
# name: Terraform Dispatch

# on: [workflow_dispatch]

# jobs:
#   list-workspaces:
#     runs-on: ubuntu-latest
#     outputs:
#       workspaces: ${{ steps.get-workspaces.outputs.workspaces }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.0

#       - name: Initialize Terraform
#         run: terraform init

#       - name: List Workspaces
#         id: get-workspaces
#         run: |
#           workspaces=$(terraform workspace list | grep -oP '(?<= )[a-zA-Z0-9_-]+')
#           echo "::set-output name=workspaces::${workspaces}"




# name: Terraform CI/CD

# on:
#   workflow_run:
#     workflows: ["Terraform Dispatch"]
#     types:
#       - completed

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         workspace: ${{ fromJson(needs.list-workspaces.outputs.workspaces) }}
#     needs: list-workspaces
#     env:
#       TF_WORKSPACE: ${{ matrix.workspace }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.0

#       - name: Initialize Terraform
#         run: terraform init

#       - name: Select Workspace
#         run: terraform workspace select ${{ matrix.workspace }}

#       - name: Terraform Plan
#         if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
#         run: terraform plan -out=tfplan -input=false

#       - name: Post Plan Comment
#         if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           PLAN=$(terraform show -no-color tfplan)
#           COMMENT="### Terraform Plan for \`${{ matrix.workspace }}\` Workspace:\n\`\`\`\n$PLAN\n\`\`\`"
#           curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST \
#           -d "{\"body\":\"$COMMENT\"}" \
#           "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"

#       - name: Terraform Apply
#         if: github.event_name == 'workflow_run' && github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
#         run: terraform apply -input=false tfplan
